### ISSUE TITLE
Incognito Mode

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [FossifyOrg/Keyboard#108]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Incognito Mode - Nothing what is being typed, is tracked or used for personalisation.

### Why do you want this feature?

I love Incognito Mode from the Keyboard of FlorisBoard and I would love to have this for Fossify Keyboard too! Because what i type is my Privacy and needs to be protected.

**Comment by naveensingh** [comment]
Fossify Keyboard doesn't do personalization so you are always incognito.

**Comment by naveensingh** [comment]
> > > So you want me to just trust blindly?
> > 
> > Not at all, the code is open source for a reason.
> 
> But that does not mean that the Keyboard is automatically not saving what I type...

The source code allows you to verify what the keyboard does and how. Fossify Keyboard doesn't save/track what you type, I would be more concerned about the app where the typing is done.

> Why not just incognito and no track at all?

See https://github.com/FossifyOrg/Keyboard/issues/108#issuecomment-2488238810.

> > > So why does for example FlorisBoard add this Feature?
> >
> > They may have a feature that relies on what you are typing.
> > 
> Nope they have not.

The feature list says otherwise: https://github.com/florisboard/florisboard?tab=readme-ov-file#highlighted-features
