### ISSUE TITLE
Add to F-Droid Repository

### ISSUE THREAD

**Issue by R-Bose** [FossifyOrg/Keyboard#26]
**Checklist**
 -  - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 -  - [x]  I have read the FAQ and my problem isn't listed.
 -  - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 -  - [x]  This issue contains only one feature request.
 -  - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
For non hardcore technical users trying to install apks from GitHub repos is cumbersome and it is preferable to install apps from a store to ease downloads and updates.

**Describe the solution you'd like**
Maintain a F-Droid repo which will contain the latest releases so that users can verify downloads and stay up-to-date.

**Describe alternatives you've considered**
Google Play Store, though I assume it will be economically non feasible.

**Additional context**
There already exists repositories for Fossify Gallery, File Manager and Calendar, so might as well host all other apps there.

**Comment by Aga-C** [comment]
It will be added soon.

**Comment by Aga-C** [comment]
App wasn't released yet. When it will be released, it will also be submitted to F-Droid.

**Comment by R-Bose** [comment]
Any way to add myself to an email list when there's a release?

**Comment by naveensingh** [comment]
@R-Bose You can subscribe to https://github.com/orgs/FossifyOrg/discussions/9

More project related info is here: https://github.com/FossifyOrg#-hey-there-welcome-to-fossify

**Comment by Philippe-Choquette** [comment]
Is there a reason why Google Play availability isn't considered even though many other Fossify apps are made available there?

**Comment by naveensingh** [comment]
It is still in review and should be available by the weekend.

**Comment by naveensingh** [comment]
@Philippe-Choquette it's available now: https://play.google.com/store/apps/details?id=org.fossify.keyboard

**Comment by Philippe-Choquette** [comment]
I thought I had looked properly earlier but clearly not; thank you!
