### ISSUE TITLE
Add Esperanto language layout

### ISSUE THREAD

**Issue by flashymittens** [FossifyOrg/Keyboard#31]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please add Esperanto layout. It should likely be based on QWERTY English.

### Why do you want this feature?

Because I write in Esperanto.

### Additional information

Alphabet: <https://en.wikipedia.org/wiki/Esperanto_orthography>.

**Comment by tenextractor** [comment]
@flashymittens Is the Gboard layout ok?

```
Ŝ Ĝ E R T Ŭ U I O P
A S D F G H J K L Ĵ
Z Ĉ C V B N M
```

**Comment by tenextractor** [comment]
@flashymittens Ĥ comes after M, see the linked pull request
