### ISSUE TITLE
Add Chuvash language layout

### ISSUE THREAD

**Issue by flashymittens** [FossifyOrg/Keyboard#32]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please add Chuvash Cyrillic layout. It should likely be based on the Russian one.

### Why do you want this feature?

It's my native language and I'd like to write in it.

### Additional information

Alphabet: <https://en.wikipedia.org/wiki/Chuvash_language#Official>.

**Comment by tenextractor** [comment]
@flashymittens Here is the Gboard layout for Chuvash:

```
Й У Ӳ К Е Ӗ Н Г Ш З Х
Ф Ы В А Ӑ П Р О Л Д Э
Я Ч С Ҫ М И Т Ь Ю
```

It seems like this layout needs long presses to type a few letters (like long press В = Б). This seems inconvenient so I would like to suggest this layout instead:

```
Ё Ӑ Ӗ Ҫ Ӳ Ъ
Й Ц У К Е Н Г Ш Щ З Х
Ф Ы В А П Р О Л Д Ж Э
Я Ч С М И Т Ь Б Ю
```

Putting the extra letters on the side would probably make the keys too small and confuse the muscle memory of people who are used to the Russian layout, so I suggest this.
Which layout is better in your opinion?

**Comment by tenextractor** [comment]
@flashymittens 
![image](https://github.com/FossifyOrg/Keyboard/assets/139619642/9ad7bffd-002a-4c73-9a20-b15da33e6087)
This was the layout I added, please feel free to give any suggestions or corrections.
