### ISSUE TITLE
Configure Fossify Keyboard to be a valid Gboard replacement

### ISSUE THREAD

**Issue by LucaMkIII** [FossifyOrg/Keyboard#37]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

On my device, I have to always have at least one of a subset of keyboards available/active in my "Manage on-screen keyboards" screen. If I disable all the keyboards in that subset, Gboard becomes greyed out and active (though its toggle doesn't always show correctly). Currently, the subset includes Gboard, AnySoftKeyboard, and Microsoft SwiftKey Keyboard.

I would like Fossify Keyboard to be in that subset so that I can turn off all keyboards except Fossify Keyboard.

### Why do you want this feature?

I would like Fossify Keyboard to be in the above-mentioned subset of keyboards so that I can turn off all other keyboards besides Fossify Keyboard (and not have Gboard re-activate).

### Additional information

Here's a screen recording showing what I mean.
https://github.com/FossifyOrg/Keyboard/assets/154716373/f9c1e546-816f-4d1c-9326-1940649f65e6

I'm not sure what needs to be configured to make it work. If this behavior is unique to me, it may instead be a (device-specific) bug.

**Comment by Aga-C** [comment]
It's normal Android behavior that it always tries to revert Gboard. On my device, when I do a lot of toggling like in your video it also reverts to Gboard at some point, but when you just disable each keyboard one after another, I am able to leave only Simple Keyboard. And the behavior you've shown, I don't have like this with AnySoftKeyboard, only with Gboard.
