### ISSUE TITLE
Additional Languages

### ISSUE THREAD

**Issue by EricosEagle** [FossifyOrg/Keyboard#5]
**Checklist**
 -  - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 -  - [x]  I have read the FAQ and my problem isn't listed.
 -  - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 -  - [x]  This issue contains only one feature request.
 -  - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyX/General-Discussion?tab=readme-ov-file#contribution-rules-for-developers)

**Is your feature request related to a problem? Please describe.**
I recently switched for the long-unmaintained Openboard (which is an open source fork of the AOSP's keyboard) to SMT's Keyboard. Unfortunately, it doesn't have support for all of the languages I use (e.g. Hebrew, Russian, Japanese).

**Describe the solution you'd like**
- For most languages: Add support for their layouts
- For Japanese: The mobile layout is probably a lot of work, so support for a QWERTY layout that then converts the english I type into Japanese characters would be great.

**Describe alternatives you've considered**
Using an additional keyboard for the other languages.

**Additional context**
Consider taking reference from Openboard or any well-known alternative keyboards

**Comment by Aga-C** [comment]
@EricosEagle Can you create a separate feature request for each language you'd like to be supported? A feature request like that is not measurable - we will never be able to tell when it should be closed. With separate languages, every time someone adds a support, we can just close the issue.
