### ISSUE TITLE
Sticky keys

### ISSUE THREAD

**Issue by brandje41** [FossifyOrg/Keyboard#51]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung Galaxy S23

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Use Keyboard, type text.
2. At random, keys will stick in the 'pressed' animation. The 'key pressed' animation is not restored to the normal unpressed state.
* Behaviour is random as far as I can tell. Seems to be triggered by typing quickly. State is restored when key is pressed again.

### Expected behavior

Keys should revert to inactive state animation after being pressed.

### Actual behavior

Keys at random get stuck at 'key pressed' animation.

### Screenshots/Screen recordings

<img alt="IMG-20240720-WA0003" src="https://github.com/user-attachments/assets/bb2462ac-2827-4629-a9a6-10f8d6a63ec6" width=300 />

**Comment by Rajala1404** [comment]
Same here

**Comment by Isakovsky92** [comment]
Same here too.

**Comment by PrivacyFriendlyMuffins** [comment]
Same here.

**Comment by brandje41** [comment]
Fix confirmed, unable to reproduce the issue with version 1.1.0
