### ISSUE TITLE
When adding more than 1 item to the clipboard, it only saves the last one.

### ISSUE THREAD

**Issue by Farajo001** [FossifyOrg/Keyboard#65]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 8.0.1

### Affected device model

Moto E5 Play

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Try to copy/cut any piece of text
2. After that, you do it again with another one
3. When you open the keyboard's clipboard only the latest one is saved

### Expected behavior

The expected behaviour should be that multiple items should be saved in the clipboard without me having to go ahead and pinning them

### Actual behavior

Only the last item appears on the list

### Additional information

If this is a feature and not a bug, then it's disappointing since I have a use case scenario in which involves copying and pasting multiple items from Pastebin.com and I want to do one trip, not multiple.

**Comment by Aga-C** [comment]
We rely on Android's ClipboardManager, and it allows access only to the last clipboard item. We would need to monitor clipboard usage 24/7 to achieve it, and we don't want to do this.

**Comment by sosasees** [comment]
i have an idea to mitigate this: timed pins

next to the pin&nbsp;button for the recent&nbsp;item, there could be another pin&nbsp;button that pins the item for only 30&nbsp;minutes before deleting the pin
